#ifndef MikeMooly_FCUIControlDef_h
#define MikeMooly_FCUIControlDef_h

enum CONTROL_BUTTON_STATE
{
    CONTROL_BUTTON_STATE_NONE,
    CONTROL_BUTTON_STATE_SELECT,
    CONTROL_BUTTON_STATE_DISABLE,
};

enum CONTROL_CHECK_BUTTON_STATE
{
    CONTROL_CHECK_BUTTON_STATE_NONE,
    CONTROL_CHECK_BUTTON_STATE_CHECKED,
};

#endif
